# Generated by Django 4.1.6 on 2023-02-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG_messages', '0002_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
